extends "res://tests/test_player_interaction.gd"
func _initialize() -> void:
	var source:=FileAccess.get_file_as_string("res://tests/golden/frontier-day-01.json")
	var packed:=SaveArchive.encode(source);var decoded:=SaveArchive.decode(packed)
	check(decoded.ok and decoded.text==source,"gzip envelope preserves exact UTF-8 JSON")
	check(SaveArchive.decode(source.to_utf8_buffer()).text==source,"legacy plain JSON accepted unchanged")
	check(not SaveArchive.decode(PackedByteArray()).ok,"empty file rejected")
	check(not SaveArchive.decode("RIMTOWN9unknown".to_utf8_buffer()).ok,"future version rejected")
	check(not SaveArchive.decode(packed.slice(0,20)).ok,"truncated envelope rejected")
	var damaged:=packed.duplicate();damaged[16]=damaged[16]^1
	check(not SaveArchive.decode(damaged).ok,"digest corruption rejected")
	damaged=packed.duplicate();damaged.encode_u64(8,SaveArchive.LIMIT+1)
	check(not SaveArchive.decode(damaged).ok,"declared expansion above limit rejected before decompress")
	var path:="/private/tmp/rimtown-archive-test-%d.rimtown"%Time.get_ticks_usec()
	check(SaveArchive.write_new(path,packed),"verified temporary file renamed")
	check(not FileAccess.file_exists(path+".writing"),"no partial file after success")
	check(not SaveArchive.write_new(path,"overwrite".to_utf8_buffer()) and FileAccess.get_file_as_bytes(path)==packed,"existing file never overwritten")
	DirAccess.remove_absolute(path)
	check(not SaveArchive.write_new("/private/tmp/rimtown-no-such-dir/sub/save.rimtown",packed),"failed destination reported")
	# Real progression artifact produced by test_main_route_progression.gd, not an inflated padding fixture.
	source=FileAccess.get_file_as_string("res://tests/main-route-ready.json.tmp")
	check(not source.is_empty(),"130-day source checkpoint available")
	packed=SaveArchive.encode(source);decoded=SaveArchive.decode(packed)
	check(decoded.ok and decoded.text==source,"real long-running history lossless")
	var w:=SimWorld.new();w.load_snapshot(JSON.parse_string(decoded.text));check(SimQuests.choose_finale(w,"legend"),"compressed pending finale selects normally")
	var frozen: Dictionary=w.data.multiEnding.endingData.duplicate(true)
	for i in 96*10: w.tick()
	check(w.data.multiEnding.endingTriggered=="legend" and equal(frozen,w.data.multiEnding.endingData),"ten post-ending days preserve frozen ending")
	var after:=JSON.stringify(w.snapshot(),"",false,true);var restored:=SimWorld.new();var continued:=SaveArchive.encode(after)
	restored.load_snapshot(JSON.parse_string(SaveArchive.decode(continued).text))
	check(equal(w.snapshot(),restored.snapshot()),"continued large save restores all simulation state")
	w.tick();restored.tick();check(equal(w.snapshot(),restored.snapshot()),"RNG and next tick deterministic after reload")
	var export_path:=ProjectSettings.globalize_path("res://../../../outputs/第140天結局後.rimtown")
	if FileAccess.file_exists(export_path): DirAccess.remove_absolute(export_path)
	check(SaveArchive.write_new(export_path,continued),"post-ending test checkpoint delivered")
	var report:={"checks":checks,"failures":failures,"day130_json_bytes":source.to_utf8_buffer().size(),"day130_archive_bytes":packed.size(),"continued_json_bytes":after.to_utf8_buffer().size(),"continued_archive_bytes":continued.size(),"scope":"lossless envelope and legacy JSON, integrity/size/version checks, no-overwrite writes, actual 130-day checkpoint then ten post-ending days and deterministic reload; no cloud upload"}
	FileAccess.open("res://docs/SAVE_ARCHIVE_TESTS.json",FileAccess.WRITE).store_string(JSON.stringify(report,"  "));print(JSON.stringify(report));quit(0 if failures.is_empty() else 1)
