extends "res://tests/test_careers.gd"
func _initialize() -> void:
	var w:=world();var before:=w.snapshot();SimAppointments.tick(w)
	check(equal(before,w.snapshot()),"old saves without appointments untouched")
	check(not SimAppointments.offer(w,"missing").is_empty() and SimAppointments.current(w).is_empty(),"missing resident rejected")
	SimAppointments.offer(w,"chen_wei","fake");check(SimAppointments.current(w).is_empty(),"invalid venue rejected")
	SimAppointments.offer(w,"chen_wei");var a:=SimAppointments.current(w)
	check(a.state=="offered" and int(a.due)>int(w.data.tickCount)+32,"future offer created")
	SimAppointments.offer(w,"lin_mei");check(a.npc=="chen_wei","cannot replace active offer")
	check(SimAppointments.respond(w,false) and a.state=="declined","decline does not schedule")
	SimAppointments.offer(w,"lin_mei");check(a.state=="declined","daily limit prevents repeated invitations")
	w=world();SimAppointments.offer(w,"chen_wei");a=SimAppointments.current(w);w.data.tickCount=a.expires
	check(not SimAppointments.respond(w,true) and a.state=="expired","late acceptance rejected")
	w=world();SimAppointments.offer(w,"chen_wei");SimAppointments.respond(w,true);a=SimAppointments.current(w)
	var restored:=SimWorld.new();restored.load_snapshot(w.snapshot())
	check(equal(a,SimAppointments.current(restored)),"accepted appointment survives save")
	w.tick();restored.tick();check(equal(w.snapshot(),restored.snapshot()),"appointment next tick deterministic")
	w.data.agents.chen_wei._raidShelterUntil=999;SimAppointments.tick(w)
	check(a.state=="cancelled" and "避難" in a.reason,"raid cancels with reason")
	check(w.data.agents.player.memory.any(func(m): return "避難" in m.content),"cancellation remembered")
	w=world();SimAppointments.offer(w,"chen_wei");SimAppointments.respond(w,true);a=SimAppointments.current(w)
	w.data.agents.chen_wei.needs.rest=0;SimAppointments.tick(w);check(a.state=="accepted","pre-meeting need allows normal recovery")
	w.data.tickCount=a.due;SimAppointments.tick(w);check(a.state=="cancelled","urgent needs at meeting cancel")
	w=world();SimAppointments.offer(w,"chen_wei");SimAppointments.respond(w,true);a=SimAppointments.current(w)
	w.data.agents.chen_wei.job={"work_hours":[0,23]};SimAppointments.tick(w);check(a.state=="cancelled" and "工作" in a.reason,"changed work schedule cancels")
	w=world();SimAppointments.offer(w,"chen_wei");SimAppointments.respond(w,true);a=SimAppointments.current(w)
	w.data.tickCount=a.until;SimAppointments.tick(w)
	check(a.state=="missed" and "尚未抵達" in a.reason,"logical destination cannot count as arrival")
	var count: int=w.quest_balance.appointments.history.size();SimAppointments.tick(w);SimAppointments.finish(w,"met","fake")
	check(w.quest_balance.appointments.history.size()==count,"terminal result exactly once")
	w=world();var parsed:=SimPlayerChat.parse("要不要明天找時間見面？\nEFFECTS: {\"affinity_change\":0,\"romantic_change\":0,\"summary\":\"邀約\",\"invitation\":true}")
	var result:=SimPlayerChat.apply(w,"chen_wei","聊聊吧",parsed)
	check(result.has("appointment") and SimAppointments.current(w).state=="offered","structured chat creates pending card")
	w=world();parsed=SimPlayerChat.parse("明天見。\nEFFECTS: {\"invitation\":\"true\"}");SimPlayerChat.apply(w,"chen_wei","你好",parsed)
	check(SimAppointments.current(w).is_empty(),"wrong field type does not create schedule")
	w=world();parsed=SimPlayerChat.parse("明天見。\nEFFECTS: {}");SimPlayerChat.apply(w,"chen_wei","你好",parsed)
	check(SimAppointments.current(w).is_empty(),"unstructured promise not treated as schedule")
	w=world();SimAppointments.offer(w,"chen_wei");SimAppointments.respond(w,true);a=SimAppointments.current(w)
	w.data.tickCount=int(a.due)-20;w.data.clock.hour=14
	check(not SimAppointments.directing(w,"chen_wei"),"appointment does not interrupt work")
	w.data.clock.hour=18
	check(SimAppointments.directing(w,"chen_wei"),"free resident departs during travel window")
	a.npc_arrived=true;w.data.tickCount=a.until;SimAppointments.tick(w)
	check(a.state=="missed" and "玩家未到" in a.reason,"arrived NPC absence has distinct reason")
	var report:={"checks":checks,"failures":failures,"scope":"offer/accept/decline/expiry, limits, conflicts and memory, save deterministic reload, chat structured invitation and no logical arrival shortcut; configured conflict fixtures"}
	FileAccess.open("res://docs/APPOINTMENTS_TESTS.json",FileAccess.WRITE).store_string(JSON.stringify(report,"  "));print(JSON.stringify(report));quit(0 if failures.is_empty() else 1)
