// Compile only the three upstream local dialogue functions into native GDScript.
// No JavaScript interpreter, network, or Node dependency in the shipped game.
import fs from 'node:fs';import vm from 'node:vm';import path from 'node:path';import {root,sha} from './golden.mjs';
const exports={};vm.runInNewContext(process.binding('natives')['internal/deps/acorn/acorn/dist/acorn'],{exports,module:{exports}});
const source=fs.readFileSync(path.join(root,'chrome-extension/simulation.js'),'utf8');
const tree=exports.parse(source,{ecmaVersion:'latest'});const cls=tree.body.find(n=>n.type==='ClassDeclaration'&&n.id.name==='ConversationEngine');
const names=['_generatePersonalityDialogue','_personalityGreeting','_addConflictEscalation'];let closures=[],counter=0;
const quote=JSON.stringify;
function expr(n){if(!n)return 'null';switch(n.type){
case 'Literal':if(n.regex){if(n.regex.pattern==='_')return quote('_');throw Error('regex '+n.regex.pattern);}return quote(n.value);
case 'Identifier':return n.name==='undefined'?'null':`s.get(${quote(n.name)})`;
case 'ChainExpression':return expr(n.expression);
case 'ArrayExpression':return '['+n.elements.map(expr).join(',')+']';
case 'ObjectExpression':return '{'+n.properties.map(p=>quote(p.key.name??p.key.value)+':'+expr(p.value)).join(',')+'}';
case 'MemberExpression':return `_property(${expr(n.object)},${n.computed?expr(n.property):quote(n.property.name)})`;
case 'TemplateLiteral':return '('+n.quasis.flatMap((q,i)=>[quote(q.value.cooked),...(n.expressions[i]?[`str(${expr(n.expressions[i])})`]:[])]).join('+')+')';
case 'ConditionalExpression':return `(${expr(n.consequent)} if _truth(${expr(n.test)}) else ${expr(n.alternate)})`;
case 'LogicalExpression':return `${{'||':'_or','&&':'_and','??':'_coalesce'}[n.operator]}(${expr(n.left)},func(): return ${expr(n.right)})`;
case 'UnaryExpression':if(n.operator==='!')return `(not _truth(${expr(n.argument)}))`;if(n.operator==='-')return `(-${expr(n.argument)})`;break;
case 'BinaryExpression':return `(${expr(n.left)} ${{'===':'==','!==':'!='}[n.operator]??n.operator} ${expr(n.right)})`;
case 'ArrowFunctionExpression':{const name='_topic_'+counter++;closures.push({name,node:n});return quote(name);}
case 'CallExpression':{
 const args=n.arguments.map(expr).join(',');const c=n.callee;
 if(c.type==='Identifier'){if(c.name==='t')return expr(n.arguments[0]);if(c.name==='pickRandom')return `rng.pick(${args})`;if(c.name==='randInt')return `rng.next_int(${args})`;}
 if(c.type==='MemberExpression'){
  const m=c.property.name;
  if(c.object.name==='Personality'&&m==='compatibility')return `compatibility(${args})`;
  if(c.object.type==='ThisExpression')return `${m}(${args})`;
  if(c.object.name==='Math'){if(m==='random')return 'rng.next_float()';if(['min','max','abs','round'].includes(m))return `${{min:'min',max:'max',abs:'abs',round:'_round'}[m]}(${args})`;}
  if(m==='includes')return `_includes(${expr(c.object)},${args})`;
  if(m==='replace')return `str(${expr(c.object)}).replace(${args})`;
  if(m==='push')return `_push(${expr(c.object)},${args})`;
 }
 if(c.type==='CallExpression')return `call(${expr(c)},s)`;
 throw Error('Unsupported call '+source.slice(n.start,n.end));}
}throw Error('Unsupported expression '+n.type);}
function statement(n,indent=1){const t='\t'.repeat(indent);switch(n.type){
case 'BlockStatement':return n.body.map(x=>statement(x,indent)).join('');
case 'VariableDeclaration':return n.declarations.map(d=>`${t}s[${quote(d.id.name)}]=${expr(d.init)}\n`).join('');
case 'ExpressionStatement':if(n.expression.type==='AssignmentExpression'){const a=n.expression;if(a.left.type!=='Identifier')throw Error('member assignment');return `${t}s[${quote(a.left.name)}] ${a.operator} ${expr(a.right)}\n`;}return t+expr(n.expression)+'\n';
case 'IfStatement':return `${t}if _truth(${expr(n.test)}):\n${statement(n.consequent,indent+1)}`+(n.alternate?`${t}else:\n${statement(n.alternate,indent+1)}`:'');
case 'ReturnStatement':return t+'return '+expr(n.argument)+'\n';
}throw Error('Unsupported statement '+n.type);}
let output=`class_name SimDialogue\nextends RefCounted\n# Generated by tools/build_dialogue.mjs; edit the compiler, not this file.\n# Upstream simulation.js SHA256: ${sha(source)}\nvar rng: SimRandom\n`;
for(const name of names){const node=cls.body.body.find(x=>x.key.name===name).value;const params=node.params.map(x=>x.name);output+=`func ${name}(${params.map(x=>x+': Variant').join(',')}) -> Variant:\n\tvar s: Dictionary={${params.map(x=>quote(x)+':'+x).join(',')}}\n`+statement(node.body)+'\treturn null\n';}
for(let i=0;i<closures.length;i++){const {name,node}=closures[i];output+=`func ${name}(s: Dictionary) -> Variant:\n`+statement(node.body)+'\treturn null\n';}
output+=`static func compatibility(a: Array,b: Array) -> float:
	var score:=0
	for pair in [["kind","kind"],["creative","creative"],["optimist","optimist"],["kind","shy"],["charismatic","shy"],["hardworking","hardworking"],["romantic","romantic"],["stoic","neurotic"]]:
		if (pair[0] in a and pair[1] in b) or (pair[1] in a and pair[0] in b): score+=1
	for pair in [["abrasive","shy"],["abrasive","kind"],["pessimist","optimist"],["lazy","hardworking"],["lazy","perfectionist"],["jealous","charismatic"],["neurotic","neurotic"],["gossip","stoic"]]:
		if (pair[0] in a and pair[1] in b) or (pair[1] in a and pair[0] in b): score-=1
	return clampf(1.0+score*.3,.2,1.6)
static func _truth(value: Variant) -> bool:
	if value == null: return false
	if value is bool: return value
	if value is int or value is float: return value != 0
	if value is String: return not value.is_empty()
	return true
static func _property(value: Variant,key: Variant) -> Variant:
	if value is Dictionary: return value.get(key)
	if value is Array:
		if key is String and key == "length": return value.size()
		if key is int or key is float:
			return value[int(key)] if int(key)>=0 and int(key)<value.size() else null
	return null
static func _or(value: Variant,other: Callable) -> Variant:
	return value if _truth(value) else other.call()
static func _and(value: Variant,other: Callable) -> Variant:
	return other.call() if _truth(value) else value
static func _coalesce(value: Variant,other: Callable) -> Variant:
	return other.call() if value==null else value
static func _includes(value: Variant,item: Variant) -> bool:
	return item in value
static func _push(values: Array,item: Variant) -> int:
	values.append(item)
	return values.size()
static func _round(value: float) -> int:
	return floori(value+.5)
`;
fs.writeFileSync(path.join(root,'godot/scripts/sim/sim_dialogue.gd'),output);console.log('Compiled dialogue functions and',closures.length,'topic closures');
