import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {context,root} from './golden.mjs';
const raw=JSON.parse(fs.readFileSync(path.join(root,'godot/tests/golden/frontier-day-01.json')));const cases=[];
for(const mode of ['main','npc'])for(const level of [0,20,40,65,100]){
 const c=context();Object.assign(c.ctx,{raw,level});vm.runInContext(`for(const q of MAIN_QUESTS)for(const r of q.routes||[])for(const c of r.conditions)if(c.target===undefined)c.target=1;var w=new World();w.loadSave(raw);w.questSystem=new QuestSystem();w.questSystem.init();w.npcQuests=new NPCQuestSystem();for(const k of Object.keys(w.stockpile.resources))w.stockpile.resources[k]=level*100;for(const a of Object.values(w.agents)){a.moodModifier=0;if(!a.isPlayer){var rel=w.agents.player.relationships.getOrCreate(a.agentId,a.name);rel.affinity=level;}}w.questSystem.chatCount=level;w.questSystem.tradeCount=level;w.questSystem.harvestCount=level;w.questSystem.reputation=level*10;w.questSystem.electionsHeld=level;w.questSystem.raidsSurvived=level;`,c.ctx);
 const input=JSON.parse(vm.runInContext('JSON.stringify(w.serialize())',c.ctx));c.setRandomState(11456);
 for(let i=0;i<8;i++)vm.runInContext(mode==='main'?'w.questSystem.checkProgress(w)':'w.npcQuests._checkTriggers(w);w.npcQuests._checkProgress(w);w.npcQuests._updateIndustryBonuses(w)',c.ctx);
 const out=JSON.parse(vm.runInContext('JSON.stringify(w.serialize())',c.ctx));cases.push({mode,input,expected:{questSystem:out.questSystem,npcQuests:out.npcQuests,stockpile:out.stockpile,messageLog:out.messageLog,dailyNews:out.dailyNews},moods:JSON.parse(vm.runInContext('JSON.stringify(Object.fromEntries(Object.entries(w.agents).map(([id,a])=>[id,a.moodModifier||0])))',c.ctx)),rng:c.getRandomState()});
}
const c=context();c.ctx.raw=raw;vm.runInContext('var w=new World();w.loadSave(raw)',c.ctx);const conditions=vm.runInContext('MAIN_QUESTS.flatMap(q=>q.objectives||q.routes.flatMap(r=>r.conditions)).concat(SIDE_QUESTS.flatMap(q=>q.objectives),DAILY_OBJECTIVES.map(d=>d.condition),Object.values(NPC_PERSONAL_QUESTS).flatMap(n=>n.quests.flatMap(q=>q.routes.flatMap(r=>r.conditions))))',c.ctx);const evaluated=conditions.map(cond=>{c.ctx.cond=cond;return {cond,main:vm.runInContext('w.questSystem._evaluateCondition(cond,w)',c.ctx),npc:vm.runInContext('w.npcQuests._evaluateCondition(cond,w,w.agents.player,"chen_wei")',c.ctx)}});
fs.mkdirSync(path.join(root,'godot/tests/quests'),{recursive:true});fs.writeFileSync(path.join(root,'godot/tests/quests/oracle.json'),JSON.stringify({cases,conditionInput:JSON.parse(vm.runInContext('JSON.stringify(w.serialize())',c.ctx)),evaluated}));console.log(cases.length,evaluated.length);
