class_name SimDialogue
extends RefCounted
# Generated by tools/build_dialogue.mjs; edit the compiler, not this file.
# Upstream simulation.js SHA256: 6db2dacf6c6a61a8f1a0e3ab7332cf507213c5c5e6c3b4961ca7c349bfaa3654
var rng: SimRandom
func _generatePersonalityDialogue(agentA: Variant,agentB: Variant,world: Variant,relA: Variant,relB: Variant) -> Variant:
	var s: Dictionary={"agentA":agentA,"agentB":agentB,"world":world,"relA":relA,"relB":relB}
	s["tA"]=_property(_property(s.get("agentA"),"personality"),"traits")
	s["tB"]=_property(_property(s.get("agentB"),"personality"),"traits")
	s["jobA"]=_or(_property(_property(s.get("agentA"),"job"),"title"),func(): return "無業")
	s["jobB"]=_or(_property(_property(s.get("agentB"),"job"),"title"),func(): return "無業")
	s["loc"]=str(_property(s.get("agentA"),"currentLocation")).replace("_"," ")
	s["timeOfDay"]=_property(_property(s.get("world"),"clock"),"timeOfDay")
	s["season"]=_property(_property(s.get("world"),"clock"),"season")
	s["lines"]=[]
	s["affA"]=0
	s["affB"]=0
	s["romA"]=0
	s["romB"]=0
	s["summary"]=""
	s["foods"]={"春季":["野菜煎餅","花瓣蜜茶","春筍燉肉","桂花糕","薺菜餛飩"],"夏季":["冰鎮酸梅湯","西瓜","涼拌黃瓜","綠豆湯","荷葉飯"],"秋季":["烤地瓜","桂花釀","栗子燒雞","蘋果派","南瓜濃湯"],"冬季":["薑母茶","熱騰騰的羊肉鍋","烤紅薯","熱奶酒","麻辣火鍋"]}
	s["scenery"]={"春季":["櫻花飄落的小徑","河邊盛開的野花","清晨帶著露水的草地"],"夏季":["星空下的河流","螢火蟲飛舞的夜晚","午後蟬鳴的樹蔭下"],"秋季":["金黃落葉鋪滿的石板路","楓紅染遍山頭的景色","豐收後堆滿穀物的倉庫"],"冬季":["白雪覆蓋的屋頂","壁爐旁搖曳的火光","冬夜裡遠處傳來的狼嚎"]}
	s["gifts"]=["一束剛採的野花","自己做的手工餅乾","一瓶私藏的好酒","昨天釣到的魚做成的魚乾","一條手織的圍巾","用漂亮石頭做的小飾品"]
	s["rumors"]=[(""+str("聽說")+""+str(rng.pick(["雜貨店","酒館","鎮公所"]))+""+str("昨晚有人看到奇怪的光")+""),(""+str("據說最近森林裡出現了")+""+str(rng.pick(["罕見的白鹿","神秘的遺跡","一群外來的旅人"]))+""),(""+str("有人說")+""+str(rng.pick(["河邊","山洞","舊礦坑"]))+""+str("藏著寶藏")+""),(""+str("聽說隔壁的商隊帶來了")+""+str(rng.pick(["稀有香料","遠方的書信","神秘的藥草"]))+"")]
	s["food"]=rng.pick(_or(_property(s.get("foods"),s.get("season")),func(): return _property(s.get("foods"),"春季")))
	s["scene"]=rng.pick(_or(_property(s.get("scenery"),s.get("season")),func(): return _property(s.get("scenery"),"春季")))
	s["isCouple"]=_or((_property(s.get("relA"),"status") == "dating"),func(): return (_property(s.get("relA"),"status") == "married"))
	s["isCrush"]=_or((_property(s.get("relA"),"romanticInterest") > 50),func(): return (_property(s.get("relB"),"romanticInterest") > 50))
	s["isRival"]=_or((_property(s.get("relA"),"affinity") < (-20)),func(): return (_property(s.get("relB"),"affinity") < (-20)))
	s["isCloseFriend"]=_and((_property(s.get("relA"),"affinity") > 50),func(): return (_property(s.get("relB"),"affinity") > 50))
	s["isStranger"]=(_property(s.get("relA"),"interactionCount") < 3)
	s["greetA"]=_personalityGreeting(s.get("agentA"),s.get("agentB"),s.get("relA"))
	s["greetB"]=_personalityGreeting(s.get("agentB"),s.get("agentA"),s.get("relB"))
	if _truth(s.get("isCouple")):
		s["coupleTopics"]=["_topic_0","_topic_1","_topic_2"]
		call(rng.pick(s.get("coupleTopics")),s)
	else:
		if _truth(s.get("isRival")):
			s["hostileTemplates"]=["_topic_3","_topic_4","_topic_5"]
			call(rng.pick(s.get("hostileTemplates")),s)
		else:
			if _truth(s.get("isCrush")):
				s["crushA"]=(_property(s.get("relA"),"romanticInterest") > 50)
				s["crushB"]=(_property(s.get("relB"),"romanticInterest") > 50)
				s["crushTopics"]=["_topic_6","_topic_7"]
				call(rng.pick(s.get("crushTopics")),s)
			else:
				if _truth(s.get("isCloseFriend")):
					s["friendTopics"]=["_topic_8","_topic_9","_topic_10"]
					call(rng.pick(s.get("friendTopics")),s)
				else:
					if _truth(s.get("isStranger")):
						s["strangerTopics"]=["_topic_11","_topic_12","_topic_13","_topic_14","_topic_15","_topic_16","_topic_17"]
						call(rng.pick(s.get("strangerTopics")),s)
					else:
						s["normalTopics"]=["_topic_18","_topic_19","_topic_20","_topic_21","_topic_22","_topic_23"]
						call(rng.pick(s.get("normalTopics")),s)
						if _truth((rng.next_float() < 0.12)):
							_addConflictEscalation(s.get("lines"),s.get("agentA"),s.get("agentB"),s.get("world"),s.get("tA"),s.get("tB"))
							s["affA"] = min(s.get("affA"),rng.next_int((-4),(-1)))
							s["affB"] = min(s.get("affB"),rng.next_int((-4),(-1)))
							s["summary"] += "但後來氣氛突然變得微妙，兩人不歡而散。"
	if _truth(_and(_and(_and(_and(_and((not _truth(s.get("isCouple"))),func(): return (not _truth(s.get("isRival")))),func(): return (s.get("affA") >= 3)),func(): return (s.get("affB") >= 3)),func(): return (_property(s.get("relA"),"affinity") > 20)),func(): return (_property(s.get("relB"),"affinity") > 20))):
		s["hasRomanticTrait"]=_or(_includes(s.get("tA"),"romantic"),func(): return _includes(s.get("tB"),"romantic"))
		s["hasChemistry"]=_or(_or(_and(_includes(s.get("tA"),"shy"),func(): return _includes(s.get("tB"),"charismatic")),func(): return _and(_includes(s.get("tB"),"shy"),func(): return _includes(s.get("tA"),"charismatic"))),func(): return _and(_includes(s.get("tA"),"creative"),func(): return _includes(s.get("tB"),"creative")))
		s["sparkChance"]=(0.3 if _truth(s.get("hasRomanticTrait")) else (0.2 if _truth(s.get("hasChemistry")) else 0.1))
		if _truth((rng.next_float() < s.get("sparkChance"))):
			s["spark"]=rng.next_int(1,(3 if _truth(s.get("hasRomanticTrait")) else (2 if _truth(s.get("hasChemistry")) else 2)))
			s["romA"] += s.get("spark")
			s["romB"] += max(0,(s.get("spark") - rng.next_int(0,1)))
	return {"lines":s.get("lines"),"_affA":s.get("affA"),"_affB":s.get("affB"),"_romA":s.get("romA"),"_romB":s.get("romB"),"_summary":s.get("summary")}
	return null
func _personalityGreeting(agent: Variant,other: Variant,rel: Variant) -> Variant:
	var s: Dictionary={"agent":agent,"other":other,"rel":rel}
	s["tr"]=_property(_property(s.get("agent"),"personality"),"traits")
	s["name"]=_property(s.get("other"),"name")
	if _truth(_or((_property(s.get("rel"),"status") == "dating"),func(): return (_property(s.get("rel"),"status") == "married"))):
		return rng.pick([(""+str("親愛的")+""+str(s.get("name"))+""+str("。")+""),(""+str(s.get("name"))+"~"),(""+str("嘿，")+""+str(s.get("name"))+""+str("。")+"")])
	if _truth(_includes(s.get("tr"),"charismatic")):
		return rng.pick([(""+str("嘿！")+""+str(s.get("name"))+""+str("！")+""),(""+str("哈囉")+""+str(s.get("name"))+""+str("，真高興見到你！")+""),(""+str(s.get("name"))+""+str("！好久不見！")+"")])
	if _truth(_includes(s.get("tr"),"shy")):
		return rng.pick([(""+str("啊...")+""+str(s.get("name"))+"..."+str("你好。")+""),"嗯...你好。","...嗨。"])
	if _truth(_includes(s.get("tr"),"abrasive")):
		return rng.pick([(""+str("喔，")+""+str(s.get("name"))+""+str("啊。")+""),"怎麼又是你。",(""+str(s.get("name"))+""+str("。")+"")])
	if _truth(_includes(s.get("tr"),"optimist")):
		return rng.pick([(""+str(s.get("name"))+""+str("！今天也是美好的一天！")+""),(""+str("嗨")+""+str(s.get("name"))+""+str("，你看起來很有精神！")+"")])
	if _truth(_includes(s.get("tr"),"pessimist")):
		return rng.pick([(""+str(s.get("name"))+"..."+str("唉。")+""),(""+str("嗯...")+""+str(s.get("name"))+""+str("。")+"")])
	return rng.pick([(""+str("嘿，")+""+str(s.get("name"))+""+str("。")+""),(""+str("你好啊，")+""+str(s.get("name"))+""+str("。")+""),(""+str("哈囉，")+""+str(s.get("name"))+""+str("！")+""),(""+str(s.get("name"))+""+str("，好久不見。")+"")])
	return null
func _addConflictEscalation(lines: Variant,agentA: Variant,agentB: Variant,world: Variant,tA: Variant,tB: Variant) -> Variant:
	var s: Dictionary={"lines":lines,"agentA":agentA,"agentB":agentB,"world":world,"tA":tA,"tB":tB}
	s["conflictTypes"]=["_topic_24","_topic_25","_topic_26","_topic_27","_topic_28"]
	call(rng.pick(s.get("conflictTypes")),s)
	return null
func _topic_0(s: Dictionary) -> Variant:
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("你今天做的")+""+str(s.get("food"))+""+str("真的太好吃了，我到現在嘴裡還有那個味道！")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":((""+str("真...真的嗎？其實我怕做得不夠好，特地多加了點")+""+str(rng.pick(["蜂蜜","香料","秘方"]))+"...") if _truth(_includes(s.get("tB"),"shy")) else (""+str("那當然！這可是我花了一整個下午的心血，為了某個人。")+""))})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":"下次讓我也給你做一頓，雖然我的手藝可能會讓你後悔..."})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("你做什麼我都喜歡，因為是你做的。" if _truth(_includes(s.get("tB"),"romantic")) else "哈哈，那我先準備好腸胃藥！")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":"你！過分！...不過我真的很幸福。"})
	s["affA"] = rng.next_int(3,6)
	s["affB"] = rng.next_int(3,6)
	s["romA"] = rng.next_int(2,4)
	s["romB"] = rng.next_int(2,4)
	s["summary"] = (""+str(s.get("loc"))+""+str("裡，")+""+str(_property(s.get("agentA"),"name"))+""+str("讚美了")+""+str(_property(s.get("agentB"),"name"))+""+str("親手做的")+""+str(s.get("food"))+""+str("，兩人甜蜜地打鬧著，笑聲讓路過的人都忍不住微笑。")+"")
	return null
func _topic_1(s: Dictionary) -> Variant:
	s["jealousA"]=_includes(s.get("tA"),"jealous")
	s["jealousB"]=_includes(s.get("tB"),"jealous")
	if _truth(_or(s.get("jealousA"),func(): return s.get("jealousB"))):
		s["j"]=(s.get("agentA") if _truth(s.get("jealousA")) else s.get("agentB"))
		s["o"]=(s.get("agentB") if _truth(s.get("jealousA")) else s.get("agentA"))
		_push(s.get("lines"),{"speaker":_property(s.get("j"),"name"),"text":"我剛剛看到你跟那個人聊了好久，你們在說什麼悄悄話？"})
		_push(s.get("lines"),{"speaker":_property(s.get("o"),"name"),"text":(""+str("就是在討論")+""+str(rng.pick(["工作的事","鎮上活動","建材價格"]))+""+str("啊，你又胡思亂想了。")+"")})
		_push(s.get("lines"),{"speaker":_property(s.get("j"),"name"),"text":"...你笑得那麼開心，我在旁邊看著心裡很不是滋味。"})
		_push(s.get("lines"),{"speaker":_property(s.get("o"),"name"),"text":("傻瓜，我心裡只有你一個人啊。來，把手給我。" if _truth(_includes(_property(_property(s.get("o"),"personality"),"traits"),"kind")) else "你能不能信任我一點？每次都這樣我也很累的。")})
		_push(s.get("lines"),{"speaker":_property(s.get("j"),"name"),"text":"...對不起。我就是太害怕失去你了。"})
		s["affA"] = rng.next_int((-1),2)
		s["affB"] = rng.next_int((-1),2)
		s["romA"] = rng.next_int(0,1)
		s["romB"] = rng.next_int(0,1)
		s["summary"] = (""+str(_property(s.get("j"),"name"))+""+str("因為看到")+""+str(_property(s.get("o"),"name"))+""+str("和別人說笑而醋意大發，兩人經歷了一場小風波，最終在")+""+str(s.get("loc"))+""+str("和好。")+"")
	else:
		_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str(s.get("season"))+""+str("的夜晚真美...你看那邊，")+""+str(s.get("scene"))+""+str("。要不要一起去走走？")+"")})
		_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("好...牽著我的手好嗎？" if _truth(_includes(s.get("tB"),"shy")) else "走啊！我還想帶你去看一個秘密地點，保證你沒去過！")})
		_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":"和你在一起的時候，覺得這個小鎮是全世界最美的地方。"})
		_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":"笨蛋...突然說這種話，我都不知道該怎麼回了。"})
		s["affA"] = rng.next_int(3,5)
		s["affB"] = rng.next_int(3,5)
		s["romA"] = rng.next_int(2,4)
		s["romB"] = rng.next_int(2,4)
		s["summary"] = (""+str(s.get("season"))+""+str("的")+""+str(s.get("loc"))+""+str("裡，")+""+str(_property(s.get("agentA"),"name"))+""+str("和")+""+str(_property(s.get("agentB"),"name"))+""+str("手牽手散步，分享著")+""+str(s.get("scene"))+""+str("的浪漫景色，氣氛溫馨而甜蜜。")+"")
	return null
func _topic_2(s: Dictionary) -> Variant:
	s["gift"]=rng.pick(s.get("gifts"))
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str(_property(s.get("agentB"),"name"))+""+str("，閉上眼睛，我有東西要給你！")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":"又在搞什麼鬼？...好啦好啦，閉上了。"})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("好了，睜開！噹噹——")+""+str(s.get("gift"))+""+str("！看到的時候就想到你了。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("......謝謝。我會好好珍藏的。" if _truth(_includes(s.get("tB"),"stoic")) else "天啊！這也太可愛了吧！你怎麼知道我一直想要這個？！")})
	s["affA"] = rng.next_int(3,6)
	s["affB"] = rng.next_int(4,7)
	s["romA"] = rng.next_int(2,3)
	s["romB"] = rng.next_int(2,4)
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("在")+""+str(s.get("loc"))+""+str("送了")+""+str(_property(s.get("agentB"),"name"))+""+str(s.get("gift"))+""+str("作為驚喜，")+""+str(_property(s.get("agentB"),"name"))+""+str(("雖然表面平靜但眼眶微紅" if _truth(_includes(s.get("tB"),"stoic")) else "感動得差點飛撲上去"))+""+str("，兩人的感情更加深厚了。")+"")
	return null
func _topic_3(s: Dictionary) -> Variant:
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("哦？")+""+str(_property(s.get("agentB"),"name"))+""+str("也在")+""+str(s.get("loc"))+""+str("啊，我還以為你早就被鎮上的人趕走了呢。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("你少在那邊冷嘲熱諷，有本事當面說清楚！" if _truth(_includes(s.get("tB"),"abrasive")) else "......你講話可以再難聽一點，我都習慣了。")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("別裝可憐了，你做過什麼你自己心裡清楚。上次")+""+str(rng.pick(["倉庫的事","選舉那件事","你在背後說的那些話"]))+""+str("，全鎮都知道。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("信不信由你。我問心無愧。" if _truth(_includes(s.get("tB"),"stoic")) else "你！——好，你記住今天說的話。遲早你會後悔的。")})
	s["affA"] = rng.next_int((-5),(-2))
	s["affB"] = rng.next_int((-5),(-2))
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("和")+""+str(_property(s.get("agentB"),"name"))+""+str("在")+""+str(s.get("loc"))+""+str("正面交鋒，針鋒相對的言語讓空氣彷彿凝結，周圍的居民紛紛側目。")+"")
	return null
func _topic_4(s: Dictionary) -> Variant:
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("聽說你最近又在到處說我")+""+str(rng.pick(["壞話","是非","不是"]))+""+str("？有種當面說啊。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":(""+str("我說的都是事實。你那個")+""+str(s.get("jobA"))+""+str("做成什麼樣子，大家有目共睹。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":("你——！我在這個鎮上付出了多少你知道嗎！？" if _truth(_includes(s.get("tA"),"neurotic")) else "笑話。等你做到我一半再來批評吧。")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("好了，我不想在這種地方吵。但你最好反省一下自己。" if _truth(_includes(s.get("tB"),"charismatic")) else "哼，走著瞧。")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":"你才該好好反省！"})
	s["affA"] = rng.next_int((-6),(-3))
	s["affB"] = rng.next_int((-6),(-3))
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("當面質問")+""+str(_property(s.get("agentB"),"name"))+""+str("散播流言蜚語的事，兩人在")+""+str(s.get("loc"))+""+str("爆發了激烈口角，怒氣沖天，場面一度失控。")+"")
	return null
func _topic_5(s: Dictionary) -> Variant:
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str(_property(s.get("agentB"),"name"))+""+str("，我們需要談談。不是為了吵架，是為了把話說開。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("......好吧。我也不想一直這樣下去。" if _truth(_includes(s.get("tB"),"kind")) else "你覺得有什麼好談的？")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":"我知道我們之間有很多誤會，但至少在鎮上要做到基本的尊重，你說呢？"})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("......我會考慮的。" if _truth(_includes(s.get("tB"),"stoic")) else "尊重是互相的。你先做到再來要求我。")})
	s["affA"] = rng.next_int((-2),1)
	s["affB"] = rng.next_int((-2),1)
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("在")+""+str(s.get("loc"))+""+str("試圖與")+""+str(_property(s.get("agentB"),"name"))+""+str("和解，但雙方仍帶著心結，氣氛雖有緩和卻依然充滿張力。")+"")
	return null
func _topic_6(s: Dictionary) -> Variant:
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":((""+str(_property(s.get("agentB"),"name"))+""+str("！你、你頭上有片落葉——我幫你拿掉！")+"") if _truth(s.get("crushA")) else s.get("greetA"))})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("啊，謝...謝謝...（心跳好快）你的手好溫暖。" if _truth(s.get("crushB")) else "哦，謝謝你啊。")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":((""+str("抱歉！我是不是太靠近了...不，我只是...你今天")+""+str(rng.pick(["聞起來好香","看起來好好看","笑容好好看"]))+""+str("。")+"") if _truth(s.get("crushA")) else (""+str("不客氣！")+""+str(s.get("season"))+""+str("嘛，到處都是落葉。")+""))})
	if _truth(s.get("crushB")):
		_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("你...你也是...（聲音越來越小）" if _truth(_includes(s.get("tB"),"shy")) else (""+str("哈哈，被你這麼一說我都不好意思了！那改天一起去喝杯")+""+str(s.get("food"))+""+str("好嗎？")+""))})
	s["romA"] = (rng.next_int(3,6) if _truth(s.get("crushA")) else rng.next_int(0,2))
	s["romB"] = (rng.next_int(3,6) if _truth(s.get("crushB")) else rng.next_int(0,2))
	s["affA"] = rng.next_int(2,5)
	s["affB"] = rng.next_int(2,5)
	s["who"]=("兩人" if _truth(_and(s.get("crushA"),func(): return s.get("crushB"))) else (_property(s.get("agentA"),"name") if _truth(s.get("crushA")) else _property(s.get("agentB"),"name")))
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("幫")+""+str(_property(s.get("agentB"),"name"))+""+str("拿掉頭上的落葉時兩人靠得很近，")+""+str(s.get("who"))+""+str("的臉頰微微泛紅，")+""+str(s.get("loc"))+""+str("的空氣中瀰漫著微妙的心動氣息。")+"")
	return null
func _topic_7(s: Dictionary) -> Variant:
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str(_property(s.get("agentB"),"name"))+""+str("，你知道嗎？我昨晚看到了")+""+str(s.get("scene"))+""+str("，第一個想到的人就是你。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("真的嗎...其實我也常常想著——啊不，我是說，那一定很美！" if _truth(s.get("crushB")) else "哦？聽起來很美呢。")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":"下次一定要帶你去看。跟你在一起的時候，什麼風景都會更美。"})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("...好。一定要說到做到哦。" if _truth(s.get("crushB")) else ("你真會說話！好啊，到時候再說。" if _truth(_includes(s.get("tB"),"kind")) else "嗯...好啊。"))})
	s["romA"] = (rng.next_int(2,5) if _truth(s.get("crushA")) else rng.next_int(1,2))
	s["romB"] = (rng.next_int(2,5) if _truth(s.get("crushB")) else rng.next_int(1,2))
	s["affA"] = rng.next_int(2,5)
	s["affB"] = rng.next_int(2,4)
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("在")+""+str(s.get("loc"))+""+str("和")+""+str(_property(s.get("agentB"),"name"))+""+str("分享了")+""+str(s.get("scene"))+""+str("的美景，話語間暗藏著告白的勇氣，")+""+str(_property(s.get("agentB"),"name"))+""+str(("也悄悄地紅了耳朵" if _truth(s.get("crushB")) else "禮貌地微笑回應"))+""+str("。")+"")
	return null
func _topic_8(s: Dictionary) -> Variant:
	s["rumor"]=rng.pick(s.get("rumors"))
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str(_property(s.get("agentB"),"name"))+""+str("！你一定不相信我剛聽到什麼——")+""+str(s.get("rumor"))+""+str("！")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("什麼！？快跟我說清楚！細節呢！？" if _truth(_includes(s.get("tB"),"gossip")) else "真的假的？你確定不是誰在胡說八道？")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("千真萬確！好幾個人都這麼說。要不要找個時間一起去")+""+str(rng.pick(["看看","調查","確認"]))+""+str("？")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("嗯...小心為上，但如果是真的就太刺激了！" if _truth(_includes(s.get("tB"),"kind")) else (""+str("走啊！怕什麼！帶上")+""+str(s.get("food"))+""+str("我們來場冒險！")+""))})
	s["affA"] = rng.next_int(3,5)
	s["affB"] = rng.next_int(3,5)
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("興沖沖地在")+""+str(s.get("loc"))+""+str("和摯友")+""+str(_property(s.get("agentB"),"name"))+""+str("分享了一個驚天八卦，兩人越聊越起勁，甚至約好了一起去探個究竟，氣氛既神秘又興奮。")+"")
	return null
func _topic_9(s: Dictionary) -> Variant:
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("唉...")+""+str(_property(s.get("agentB"),"name"))+""+str("，你能不能幫我出出主意？最近")+""+str(rng.pick([(""+str(s.get("jobA"))+""+str("的工作壓力大到快喘不過氣")+""),"跟隔壁的鄰居鬧了點不愉快","一直在做同一個奇怪的夢"]))+"...")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":((""+str("怎麼了？慢慢說，我聽著呢。先喝口")+""+str(s.get("food"))+""+str("暖暖。")+"") if _truth(_includes(s.get("tB"),"kind")) else (""+str("又怎麼了？你最近也太多煩惱了吧——不過說吧，反正你也憋不住。")+""))})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":"你真的是全鎮最了解我的人...每次跟你聊完心裡就踏實多了。"})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":(""+str("別肉麻了！不過...有你當朋友我也很慶幸啦。來，我請你吃")+""+str(rng.pick(["剛烤好的麵包","酒館的招牌菜","剛摘的水果"]))+""+str("。")+"")})
	s["affA"] = rng.next_int(3,6)
	s["affB"] = rng.next_int(3,5)
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("在")+""+str(s.get("loc"))+""+str("向摯友")+""+str(_property(s.get("agentB"),"name"))+""+str("傾訴了最近的煩惱，")+""+str(_property(s.get("agentB"),"name"))+""+str("耐心傾聽並貼心地準備了")+""+str(s.get("food"))+""+str("，兩人之間的友誼更加堅定了。")+"")
	return null
func _topic_10(s: Dictionary) -> Variant:
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str(_property(s.get("agentB"),"name"))+""+str("，還記得我們剛來邊境鎮那天嗎？什麼都沒有，就兩個人站在空蕩蕩的廣場上。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":"記得啊！那時候你還摔了一跤，臉都栽進泥巴裡哈哈哈哈！"})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":"你就記這個！？那你還不是迷路了三次才找到酒館！"})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":"好了好了，我們扯平。不過認真的...能跟你一起在這裡打拼，我覺得這輩子值了。"})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":"...你今天不準再說催淚的話了，我眼眶已經紅了。"})
	s["affA"] = rng.next_int(4,7)
	s["affB"] = rng.next_int(4,7)
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("和")+""+str(_property(s.get("agentB"),"name"))+""+str("在")+""+str(s.get("loc"))+""+str("回憶起初來邊境鎮的趣事，笑淚交織之間，深厚的友情讓旁人都為之動容。")+"")
	return null
func _topic_11(s: Dictionary) -> Variant:
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":((""+str("嘿！你是新面孔吧？我是")+""+str(_property(s.get("agentA"),"name"))+""+str("，在這邊做")+""+str(s.get("jobA"))+""+str("的。歡迎來到邊境鎮！")+"") if _truth(_includes(s.get("tA"),"charismatic")) else (""+str("你好...我好像沒見過你？")+""))})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":((""+str("嗯...我是")+""+str(_property(s.get("agentB"),"name"))+"..."+str("你好。這裡的")+""+str(s.get("food"))+""+str("看起來好好吃...")+"") if _truth(_includes(s.get("tB"),"shy")) else (""+str("哈囉！我叫")+""+str(_property(s.get("agentB"),"name"))+""+str("！剛到這邊不久，請多指教！這裡比我想像中熱鬧多了。")+""))})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str(s.get("loc"))+""+str("是鎮上最")+""+str(rng.pick(["熱鬧","有意思","舒服"]))+""+str("的地方！對了，如果你想吃好料的，推薦你去試試酒館的")+""+str(s.get("food"))+""+str("，絕對不會後悔。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":(""+str("真的嗎！那我一定要去試試。謝謝你，")+""+str(_property(s.get("agentA"),"name"))+""+str("！")+"")})
	s["affA"] = rng.next_int(2,5)
	s["affB"] = rng.next_int(2,5)
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("在")+""+str(s.get("loc"))+""+str("熱情地招呼了新來的")+""+str(_property(s.get("agentB"),"name"))+""+str("，推薦了鎮上的美食")+""+str(s.get("food"))+""+str("，給")+""+str(_property(s.get("agentB"),"name"))+""+str("留下了溫暖的第一印象。")+"")
	return null
func _topic_12(s: Dictionary) -> Variant:
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str(_property(s.get("agentB"),"name"))+""+str("對吧？我聽說你是做")+""+str(s.get("jobB"))+""+str("的——正好，我一直想認識做這行的人！")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":(""+str("你認識我？啊，果然小鎮消息傳得快...對，我是")+""+str(s.get("jobB"))+""+str("。你是")+""+str(_property(s.get("agentA"),"name"))+""+str("？")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("哈哈，邊境鎮就是這樣，新人來的消息半天就全鎮都知道了。改天聊聊")+""+str(rng.pick(["工作心得","鎮上的事","生活經驗"]))+""+str("吧？")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":"好啊！期待跟你多認識。"})
	s["affA"] = rng.next_int(2,4)
	s["affB"] = rng.next_int(2,4)
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("和")+""+str(_property(s.get("agentB"),"name"))+""+str("在")+""+str(s.get("loc"))+""+str("初次交談，兩人相談甚歡，約好了改天再深入聊聊，邊境鎮又多了一段新的緣分。")+"")
	return null
func _topic_13(s: Dictionary) -> Variant:
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":("啊,抱歉!我不是故意擋路的..." if _truth(_includes(s.get("tA"),"shy")) else "喔喔,不好意思,差點撞到你。")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":(""+str("沒事沒事,是我在發呆。你是...")+""+str(_property(s.get("agentA"),"name"))+""+str("?我常在")+""+str(s.get("loc"))+""+str("看到你。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":"對啊,我幾乎天天來這。你也是這一帶的人?"})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("嗯...算是吧。那個...改天見。" if _truth(_includes(s.get("tB"),"shy")) else "是啊,以後常會碰到,多多關照囉!")})
	s["affA"] = rng.next_int(1,3)
	s["affB"] = rng.next_int(1,3)
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("和")+""+str(_property(s.get("agentB"),"name"))+""+str("在")+""+str(s.get("loc"))+""+str("不小心撞在一起,尷尬又好笑地認識了彼此。")+"")
	return null
func _topic_14(s: Dictionary) -> Variant:
	s["r"]=rng.pick(s.get("rumors"))
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("欸,你有沒有聽說?")+""+str(s.get("r"))+""+str("!")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("什麼!快跟我說詳細的!我最愛聽這種了!" if _truth(_includes(s.get("tB"),"gossip")) else "咦?我還真沒聽過,你消息真靈通。")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":"哈哈,我就是喜歡到處打聽。對了,我還沒問你叫什麼名字呢?"})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":(""+str("我是")+""+str(_property(s.get("agentB"),"name"))+""+str("。看來以後鎮上有什麼風吹草動,找你就對了!")+"")})
	s["affA"] = rng.next_int(2,4)
	s["affB"] = rng.next_int(2,4)
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("用一則八卦成功勾起")+""+str(_property(s.get("agentB"),"name"))+""+str("的興趣,兩人在")+""+str(s.get("loc"))+""+str("越聊越起勁。")+"")
	return null
func _topic_15(s: Dictionary) -> Variant:
	s["item"]=rng.pick(s.get("gifts"))
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":(""+str("欸,你手上那個是")+""+str(s.get("item"))+""+str("嗎?看起來好特別。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":("對啊!我自己弄的,還在研究怎麼做得更好。你有興趣?" if _truth(_includes(s.get("tA"),"creative")) else "喔這個啊,隨手弄的。你喜歡的話...改天送你一個?")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":"真的可以嗎!那我就不客氣了。我還不知道你名字呢。"})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("我叫")+""+str(_property(s.get("agentA"),"name"))+""+str("。以後想要就來找我,別客氣。")+"")})
	s["affA"] = rng.next_int(2,4)
	s["affB"] = rng.next_int(3,5)
	s["summary"] = (""+str(_property(s.get("agentB"),"name"))+""+str("被")+""+str(_property(s.get("agentA"),"name"))+""+str("手上的")+""+str(s.get("item"))+""+str("吸引,兩人就這麼聊開了,約好改天再見。")+"")
	return null
func _topic_16(s: Dictionary) -> Variant:
	s["grump"]=(s.get("agentA") if _truth(_or(_includes(s.get("tA"),"abrasive"),func(): return _includes(s.get("tA"),"pessimist"))) else (s.get("agentB") if _truth(_or(_includes(s.get("tB"),"abrasive"),func(): return _includes(s.get("tB"),"pessimist"))) else s.get("agentA")))
	s["other"]=(s.get("agentB") if _truth((s.get("grump") == s.get("agentA"))) else s.get("agentA"))
	_push(s.get("lines"),{"speaker":_property(s.get("grump"),"name"),"text":"新來的?這鎮上沒什麼好的,別抱太大期望。"})
	_push(s.get("lines"),{"speaker":_property(s.get("other"),"name"),"text":("哈哈,你這人真直接!不過我倒覺得這裡挺有意思的。" if _truth(_or(_includes(s.get("tB"),"optimist"),func(): return _includes(s.get("tA"),"optimist"))) else "喔...好吧,謝謝提醒。")})
	_push(s.get("lines"),{"speaker":_property(s.get("grump"),"name"),"text":(""+str("...算了,你要真遇到麻煩,來找我。我叫")+""+str(_property(s.get("grump"),"name"))+""+str("。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("other"),"name"),"text":"嘴硬心軟嘛,我懂。多謝啦!"})
	s["affA"] = rng.next_int(0,3)
	s["affB"] = rng.next_int(0,3)
	s["summary"] = (""+str(_property(s.get("grump"),"name"))+""+str("嘴上潑冷水,卻還是對新認識的")+""+str(_property(s.get("other"),"name"))+""+str("伸出了援手,反差讓人莞爾。")+"")
	return null
func _topic_17(s: Dictionary) -> Variant:
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("奇怪,我總覺得跟你特別聊得來,明明才剛認識。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":"我也有這種感覺!是不是上輩子就認識了哈哈。"})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("那以後要常一起")+""+str(rng.pick(["喝一杯","散步","看星星","吃飯"]))+""+str("啊!")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":"一言為定!能認識你真好。"})
	s["affA"] = rng.next_int(3,6)
	s["affB"] = rng.next_int(3,6)
	if _truth((compatibility(s.get("tA"),s.get("tB")) > 1)):
		s["romA"] = rng.next_int(0,2)
		s["romB"] = rng.next_int(0,2)
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("和")+""+str(_property(s.get("agentB"),"name"))+""+str("在")+""+str(s.get("loc"))+""+str("一見如故,相談甚歡,彷彿認識了很久的老友。")+"")
	return null
func _topic_18(s: Dictionary) -> Variant:
	s["discovery"]=rng.pick([(""+str("你知道嗎？我昨天在河邊發現了一種從沒見過的")+""+str(rng.pick(["發光的石頭","藍色的蘑菇","奇怪的腳印"]))+""),(""+str("我昨晚在")+""+str(rng.pick(["圖書館","禮拜堂","山丘上"]))+""+str("看到了")+""+str(rng.pick(["神秘的光","一隻從沒見過的鳥","天上有兩個月亮"]))+""),(""+str("今天早上我去")+""+str(rng.pick(["井邊打水","田裡幹活","林子裡散步"]))+""+str("的時候，聽到了")+""+str(rng.pick(["很美的歌聲","奇怪的低語","遠方傳來的鐘聲"]))+"")])
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str(_property(s.get("agentB"),"name"))+""+str("！")+""+str(s.get("discovery"))+""+str("！")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("什麼！？太神奇了！你帶我去看好不好！" if _truth(_includes(s.get("tB"),"creative")) else "真的假的？該不會是你看花眼了吧？")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":"我騙你幹嘛！千真萬確，下次遇到我馬上叫你！"})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("好吧好吧...不過要是什麼危險的東西你可要負責。" if _truth(_includes(s.get("tB"),"pessimist")) else (""+str("一言為定！記得帶上")+""+str(s.get("food"))+""+str("，探險可不能餓肚子！")+""))})
	s["affA"] = rng.next_int(2,4)
	s["affB"] = rng.next_int(2,4)
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("興奮地和")+""+str(_property(s.get("agentB"),"name"))+""+str("分享了一個神奇的發現，兩人在")+""+str(s.get("loc"))+""+str("聊得眉飛色舞，約好下次一起去探索。")+"")
	return null
func _topic_19(s: Dictionary) -> Variant:
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str(s.get("season"))+""+str("最棒的就是")+""+str(s.get("food"))+""+str("了！我剛從酒館帶了一份，要不要嚐嚐？")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("哇！好香！你也太貼心了吧——等等，你該不會有什麼事要拜託我？" if _truth(_includes(s.get("tB"),"kind")) else (""+str("還行吧，不過我比較想吃")+""+str(rng.pick(_or(_property(s.get("foods"),s.get("season")),func(): return _property(s.get("foods"),"春季"))))+""+str("。")+""))})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("被你看穿了！其實是想問你")+""+str(rng.pick(["鎮上最近有什麼新鮮事","知不知道哪裡可以買到好木材","有沒有認識會修屋頂的人"]))+""+str("。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("哈哈！先吃東西再說正事！來來來，坐下聊。" if _truth(_includes(s.get("tB"),"charismatic")) else "嗯...讓我想想，我好像聽說過一些消息。")})
	s["affA"] = rng.next_int(2,4)
	s["affB"] = rng.next_int(2,4)
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("帶了")+""+str(s.get("food"))+""+str("到")+""+str(s.get("loc"))+""+str("和")+""+str(_property(s.get("agentB"),"name"))+""+str("邊吃邊聊，")+""+str(s.get("season"))+""+str("的暖意讓兩人的對話格外愜意。")+"")
	return null
func _topic_20(s: Dictionary) -> Variant:
	s["workStory"]=rng.pick([{"a":(""+str("你不知道！今天")+""+str(s.get("jobA"))+""+str("的時候差點出大事——")+""+str(rng.pick(["一塊巨石突然滾下來","工具斷了差點傷到人","發現了一條密道"]))+""+str("！")+""),"sum":"分享了工作中驚險的一幕"},{"a":(""+str("告訴你一個祕密，")+""+str(rng.pick(["倉庫裡藏了一批沒人知道的好東西","鎮公所的地下室好像有奇怪的聲音","雜貨店老闆其實以前是個冒險家"]))+""+str("！")+""),"sum":"悄悄透露了鎮上的一個祕密"},{"a":(""+str("我今天在")+""+str(rng.pick(["工作的時候","路上","吃飯的時候"]))+""+str("碰到一件超搞笑的事——")+""+str(rng.pick(["有人把一桶水潑在鎮長身上","一隻雞追著守衛跑了三圈","有個旅人居然帶了一頭熊進酒館"]))+""+str("！")+""),"sum":"分享了一件讓人笑到肚子痛的趣事"}])
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str(_property(s.get("agentB"),"name"))+""+str("！")+""+str(_property(s.get("workStory"),"a"))+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("不會吧！？然後呢然後呢！？快說！" if _truth(_includes(s.get("tB"),"gossip")) else "哈哈哈你認真的嗎！？這也太誇張了！")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":"我發誓是真的！當場所有人都傻眼了！"})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":"這件事我要跟全鎮的人說！太精彩了！"})
	s["affA"] = rng.next_int(2,5)
	s["affB"] = rng.next_int(2,5)
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("在")+""+str(s.get("loc"))+""+str("向")+""+str(_property(s.get("agentB"),"name"))+""+str(_property(s.get("workStory"),"sum"))+""+str("，兩人笑得前仰後合，")+""+str(s.get("loc"))+""+str("裡充滿了歡樂的氣氛。")+"")
	return null
func _topic_21(s: Dictionary) -> Variant:
	s["gift"]=rng.pick(s.get("gifts"))
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("對了")+""+str(_property(s.get("agentB"),"name"))+""+str("，這個給你——")+""+str(s.get("gift"))+""+str("，上次你幫了我大忙，一直想謝謝你。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("欸...這也太...我只是舉手之勞啊，你不用這麼客氣的..." if _truth(_includes(s.get("tB"),"shy")) else "你也太有心了吧！我只是做了該做的事而已！不過...我超喜歡的，謝謝！")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":"喜歡就好！以後有什麼需要幫忙的儘管開口。"})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":"一定！你也是！...今天真的心情變好了。"})
	s["affA"] = rng.next_int(3,5)
	s["affB"] = rng.next_int(4,6)
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("在")+""+str(s.get("loc"))+""+str("送了")+""+str(_property(s.get("agentB"),"name"))+""+str(s.get("gift"))+""+str("作為感謝，")+""+str(_property(s.get("agentB"),"name"))+""+str("感動之餘兩人的友誼又更進了一步，")+""+str(s.get("season"))+""+str("的空氣裡充滿了溫暖。")+"")
	return null
func _topic_22(s: Dictionary) -> Variant:
	s["rumor"]=rng.pick(s.get("rumors"))
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("嘿")+""+str(_property(s.get("agentB"),"name"))+""+str("，你有聽說嗎？")+""+str(s.get("rumor"))+""+str("。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("真的！？我的天，這也太刺激了！你從哪裡聯來的？" if _truth(_includes(s.get("tB"),"gossip")) else "嗯？聽起來不太靠譜...不過如果是真的就有意思了。")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("好幾個人都這麼說呢！而且昨天夜裡好像真的有人看到")+""+str(rng.pick(["可疑的影子","奇怪的燈火","一群穿斗篷的人"]))+""+str("。")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("嗯...希望不是什麼壞事。不過有你一起我就安心多了。" if _truth(_includes(s.get("tB"),"kind")) else "哼，我倒要看看到底是怎麼回事。明天一起去打聽！")})
	s["affA"] = rng.next_int(2,4)
	s["affB"] = rng.next_int(2,4)
	s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("和")+""+str(_property(s.get("agentB"),"name"))+""+str("在")+""+str(s.get("loc"))+""+str("低聲討論著鎮上的神秘傳聞，越聊越覺得事情不簡單，兩人的表情既好奇又緊張。")+"")
	return null
func _topic_23(s: Dictionary) -> Variant:
	if _truth((_property(s.get("agentA"),"mood") < 20)):
		_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":(""+str(_property(s.get("agentA"),"name"))+"..."+str("你怎麼一個人坐在")+""+str(s.get("loc"))+""+str("發呆？你的眼眶是不是紅紅的...")+"")})
		_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":("...我沒事。只是在想一些事情。" if _truth(_includes(s.get("tA"),"stoic")) else "...最近什麼事都不順利，我有時候在想，我來邊境鎮到底對不對。")})
		_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":((""+str("你聽我說——你是這個鎮上不可或缺的人。我們都需要你。來，先喝口")+""+str(s.get("food"))+""+str("暖暖身子。")+"") if _truth(_includes(s.get("tB"),"kind")) else (""+str("你少來了，沒有你誰來做")+""+str(s.get("jobA"))+""+str("？鎮上離了你可不行。")+""))})
		_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("......謝謝你，")+""+str(_property(s.get("agentB"),"name"))+""+str("。有你在真好。")+"")})
		s["affA"] = rng.next_int(3,6)
		s["affB"] = rng.next_int(2,4)
		s["summary"] = (""+str(_property(s.get("agentB"),"name"))+""+str("在")+""+str(s.get("loc"))+""+str("發現了獨自落寞的")+""+str(_property(s.get("agentA"),"name"))+""+str("，溫柔地遞上一杯")+""+str(s.get("food"))+""+str("，用真摯的話語驅散了陰霾，")+""+str(_property(s.get("agentA"),"name"))+""+str("眼眶泛紅地笑了。")+"")
	else:
		if _truth((_property(s.get("agentA"),"mood") > 70)):
			_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str(_property(s.get("agentB"),"name"))+""+str("！你猜怎麼著！今天是我這輩子最好的一天——")+""+str(rng.pick(["工作順利到不可思議","發現了一個超棒的地方","有人跟我說了一句讓我開心到飛起來的話"]))+""+str("！")+"")})
			_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("你也太浮誇了...不過看你這麼開心我也忍不住笑了。" if _truth(_includes(s.get("tB"),"pessimist")) else (""+str("太好了！快跟我說！今天我請你喝")+""+str(s.get("food"))+""+str("慶祝！")+""))})
			_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("我現在覺得什麼困難都打不倒我！連")+""+str(s.get("season"))+""+str("的天氣都特別配合！")+"")})
			_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":"哈哈哈，你也太誇張了！不過...你開心我也開心，畢竟你笑起來真的很有感染力。"})
			s["affA"] = rng.next_int(2,5)
			s["affB"] = rng.next_int(2,5)
			s["summary"] = (""+str("心情大好的")+""+str(_property(s.get("agentA"),"name"))+""+str("在")+""+str(s.get("loc"))+""+str("拉著")+""+str(_property(s.get("agentB"),"name"))+""+str("分享喜悅，開懷大笑的聲音感染了整個")+""+str(s.get("loc"))+""+str("，連路過的人都忍不住嘴角上揚。")+"")
		else:
			_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str(_property(s.get("agentB"),"name"))+""+str("，你有沒有想過...如果當初沒來邊境鎮，現在會在哪裡？")+"")})
			_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":((""+str("我有時候會想呢。也許在某個大城市裡迷失方向吧...但這裡有")+""+str(s.get("scene"))+""+str("，有你們這些朋友，我不後悔。")+"") if _truth(_includes(s.get("tB"),"creative")) else (""+str("想那麼多幹嘛？現在過得不錯就好了。走，去弄點")+""+str(s.get("food"))+""+str("來吃。")+""))})
			_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":"說得也是。有時候覺得命運把我們送到這裡，一定有它的道理。"})
			_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":(""+str("少在那邊感慨了！")+""+str(s.get("food"))+""+str("可不等人，走走走！")+"")})
			s["affA"] = rng.next_int(2,4)
			s["affB"] = rng.next_int(2,4)
			s["summary"] = (""+str(_property(s.get("agentA"),"name"))+""+str("和")+""+str(_property(s.get("agentB"),"name"))+""+str("在")+""+str(s.get("loc"))+""+str("感慨起命運的安排，聊起了")+""+str(s.get("scene"))+""+str("的美好，最後被")+""+str(s.get("food"))+""+str("的香氣拉回了現實，氣氛輕鬆溫馨。")+"")
	return null
func _topic_24(s: Dictionary) -> Variant:
	s["jokes"]=[(""+str("哈哈，你知道嗎，你做的")+""+str(_or(_property(_property(s.get("agentB"),"job"),"title"),func(): return "事"))+""+str("讓我想到一個笑話——")+""),"說真的，你那個表情也太好笑了吧？",(""+str("你是不是又")+""+str(rng.pick(["偷懶","搞砸","遲到"]))+""+str("了？我開玩笑的啦。")+"")]
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":rng.pick(s.get("jokes"))})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("......這一點都不好笑。" if _truth(_includes(s.get("tB"),"stoic")) else ("你這什麼意思！？" if _truth(_includes(s.get("tB"),"neurotic")) else "呵，你覺得很幽默嗎？"))})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":("抱歉抱歉，我不是那個意思..." if _truth(_includes(s.get("tA"),"kind")) else "開不起玩笑啊？")})
	return null
func _topic_25(s: Dictionary) -> Variant:
	s["vA"]=_or(_property(_property(_property(s.get("agentA"),"personality"),"values"),0),func(): return "自由")
	s["vB"]=_or(_property(_property(_property(s.get("agentB"),"personality"),"values"),0),func(): return "秩序")
	if _truth((s.get("vA") != s.get("vB"))):
		_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str("我覺得")+""+str(s.get("vA"))+""+str("才是最重要的，你不覺得嗎？")+"")})
		_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":(""+str("我倒覺得")+""+str(s.get("vB"))+""+str("比較重要。你那種想法太天真了。")+"")})
		_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":("看法不同而已。" if _truth(_includes(s.get("tA"),"stoic")) else "哼，你不懂。")})
	else:
		_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":(""+str(_property(s.get("agentB"),"name"))+""+str("，你最近做的那件事，我覺得不太好。")+"")})
		_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":"你管太多了吧？"})
	return null
func _topic_26(s: Dictionary) -> Variant:
	s["remarks"]=[(""+str("嗯...")+""+str(_property(s.get("agentB"),"name"))+""+str("你最近是不是胖了？")+""),"有些人啊，就是不知道自己幾斤幾兩。","哦對了，上次的事你還記得吧？算了，不提了。","我不是在說你啦，不過有人最近做事真的很馬虎。"]
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":rng.pick(s.get("remarks"))})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("你在暗示什麼？有話直說！" if _truth(_includes(s.get("tB"),"abrasive")) else ("......" if _truth(_includes(s.get("tB"),"shy")) else ("你是不是在說我！？" if _truth(_includes(s.get("tB"),"neurotic")) else "...你今天怎麼了？")))})
	return null
func _topic_27(s: Dictionary) -> Variant:
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":(""+str(_property(s.get("agentA"),"name"))+""+str("，我聽說你跟別人說我")+""+str(rng.pick(["壞話","是非","閒話"]))+""+str("？")+"")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":("啊...那個...不是你想的那樣。" if _truth(_includes(s.get("tA"),"gossip")) else ("我說的都是事實。" if _truth(_includes(s.get("tA"),"abrasive")) else "什麼？我沒有啊！"))})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":("我希望以後別這樣了。" if _truth(_includes(s.get("tB"),"kind")) else "我會記住的。")})
	return null
func _topic_28(s: Dictionary) -> Variant:
	s["annoyances"]=[{"act":"一直不停地說話","resp":"你能不能安靜一會兒..."},{"act":"吃東西的聲音超大","resp":"拜託，能不能注意一下？"},{"act":"不請自來地給建議","resp":"我沒有問你的意見。"},{"act":(""+str("打斷")+""+str(_property(s.get("agentB"),"name"))+""+str("說話")+""),"resp":"你能讓我把話說完嗎！？"}]
	s["a"]=rng.pick(s.get("annoyances"))
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":("對了對了，我跟你說——" if _truth(_includes(s.get("tA"),"charismatic")) else "嗯，我覺得你應該——")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentB"),"name"),"text":_property(s.get("a"),"resp")})
	_push(s.get("lines"),{"speaker":_property(s.get("agentA"),"name"),"text":("...對不起。" if _truth(_includes(s.get("tA"),"kind")) else "切，好心沒好報。")})
	return null
static func compatibility(a: Array,b: Array) -> float:
	var score:=0
	for pair in [["kind","kind"],["creative","creative"],["optimist","optimist"],["kind","shy"],["charismatic","shy"],["hardworking","hardworking"],["romantic","romantic"],["stoic","neurotic"]]:
		if (pair[0] in a and pair[1] in b) or (pair[1] in a and pair[0] in b): score+=1
	for pair in [["abrasive","shy"],["abrasive","kind"],["pessimist","optimist"],["lazy","hardworking"],["lazy","perfectionist"],["jealous","charismatic"],["neurotic","neurotic"],["gossip","stoic"]]:
		if (pair[0] in a and pair[1] in b) or (pair[1] in a and pair[0] in b): score-=1
	return clampf(1.0+score*.3,.2,1.6)
static func _truth(value: Variant) -> bool:
	if value == null: return false
	if value is bool: return value
	if value is int or value is float: return value != 0
	if value is String: return not value.is_empty()
	return true
static func _property(value: Variant,key: Variant) -> Variant:
	if value is Dictionary: return value.get(key)
	if value is Array:
		if key is String and key == "length": return value.size()
		if key is int or key is float:
			return value[int(key)] if int(key)>=0 and int(key)<value.size() else null
	return null
static func _or(value: Variant,other: Callable) -> Variant:
	return value if _truth(value) else other.call()
static func _and(value: Variant,other: Callable) -> Variant:
	return other.call() if _truth(value) else value
static func _coalesce(value: Variant,other: Callable) -> Variant:
	return other.call() if value==null else value
static func _includes(value: Variant,item: Variant) -> bool:
	return item in value
static func _push(values: Array,item: Variant) -> int:
	values.append(item)
	return values.size()
static func _round(value: float) -> int:
	return floori(value+.5)
